function ok=chk_constraints(eps, beta, xerr, disp, prfx)
  ok = struct(...
    'A', (~eps.A_maxerr || norm(xerr.A,inf) < eps.A_maxerr) && ...
    (~eps.A_sqrerr ||  norm(xerr.A,2) <= eps.A_sqrerr),...
    'D', (~eps.D_maxerr ||  norm(xerr.D,inf) <= eps.D_maxerr) && ...
    (~eps.D_sqrerr ||  norm(xerr.D,2) <= eps.D_sqrerr));
  ok.all = ok.A && ok.D;
  if disp
    if ok.all
      ok_str = 'CONSTRAINTS MET';
    else
      ok_str = 'CONSTRAINTS NOT met';
    end
    fprintf(['%sbeta=(%10.3g %10.3g), %s\n'...
      'max_err: %10.3g(%g) %10.3g(%g), nrm_err: %10.3g(%g) %10.3g(%g)\n'],...
      prfx(),...
      beta.A, beta.D, ok_str,...
      norm(xerr.A,inf), eps.A_maxerr, norm(xerr.D,inf), eps.D_maxerr,...
      norm(xerr.A,2), eps.A_sqrerr,norm(xerr.D,2), eps.D_sqrerr);
  end
end
