[mpath,~,~] = fileparts(mfilename('fullpath'));
cd(mpath)
cd ..
trunk = pwd;
if strcmp(filesep(),'\')
    m_str = '\\trunk';
else
    m_str = sprintf('%strunk$', filesep());
end
if isempty(regexp(trunk, m_str, 'ONCE'))
    cd ..
end
cd ..
cd test_data

enc_opts = struct('process_color',true,...
  'msrmnt_mtrx',struct('type','SensingMatrixWH','args', struct('rnd_type',1)),...
  'blk_size',[72 88 2], 'blk_ovrlp',[0,0,0], ...
  'zero_ext_f',[0,0,0], 'zero_ext_b', [0,0,0], 'wrap_ext',[0,0,0],...
  'n_frames',2,...
  'msrmnt_input_ratio', {0.1,0.15,0.25}, 'random',struct('seed',1000),...
  'lossless_coder', '&CSVideoCodecInputOutputData.LLC_AC');
% enc_opts = struct('process_color',true,...
%   'msrmnt_mtrx',struct('type','SensingMatrixWH', 'args',struct()),...
%   'blk_size',[18 22 2], 'blk_ovrlp',[8, 4, 0], ...
%   'zero_ext_f',[4,0,3], 'zero_ext_b', [2,0,0], 'wrap_ext',[0,3,0],...
%   'n_frames',2,...
%   'msrmnt_input_ratio', {0.25,0.15}, 'random',struct('seed',1000),...
%   'lossless_coder', '&CSVideoCodecInputOutputData.LLC_AC');
anls_opts = [];
% dec_opts = struct('disp',0, 'expand_level', VidBlocker.BLK_STT_INTRPLT);
% dec_opts = struct('disp',1, 'expand_level', VidBlocker.BLK_STT_RAW, ...
%   'beta_A0', 0.01, 'beta_D0', 0.01, 'max_int_iters', 10, 'sparsifier', ...
%   struct('args', struct('b_stt', VidBlocker.BLK_STT_INTRPLT)));
% dec_opts = struct('disp',1, 'expand_level', VidBlocker.BLK_STT_RAW, ...
%   'beta_A0', 0.01, 'beta_D0', 0.01, 'max_int_iters', 4, 'max_iters',20, 'sparsifier', ...
%   struct('args', struct('b_stt', VidBlocker.BLK_STT_INTRPLT)));
% dec_opts = struct('disp',1);
dec_opts = struct('disp',1, 'sparsifier', struct('type', 'VidSparserTV_DCT',...
  'args', struct('motn_spec', struct(...
  'm_range', [6,6; 2,2; 1,1], ...
  'm_step_numer', [2,2;1,1;1,1], 'm_step_denom', [1,1,2],...
  'm_srch_cnt', [1,2,1],...
  'm_wait_first', [0,0,0],...
  'm_wait_next', [0,1,0]),...
  'motn_crct', 0)));
% dec_opts = struct('disp',1, 'sparsifier', struct('type', 'VidSparserMotion',...
%   'args', struct('motn_spec', struct(...
%   'm_range', [6,5; 2,2], ...
%   'm_step_numer', [2,2;1,1], 'm_step_denom', [1,1],...
%   'm_srch_cnt', [2,2],...
%   'm_wait_first', [4,2],...
%   'm_wait_next', [2,1]))));
% dec_opts = [];
ids = struct('output','*','case','Mr<Mr>Q<Qm>,<Qa><Lc><Lg>');
files_def = '<foreman_news_io.json';
% files_def = '<avi_io.json';
% cd Roger_avi

proc_opts = struct();
sml_io =  CSVidCodec.doSimulation(enc_opts,anls_opts,dec_opts,files_def, proc_opts);
