[mpath,~,~] = fileparts(mfilename('fullpath'));
cd(mpath)
cd ..
trunk = pwd;
if strcmp(filesep(),'\')
    m_str = '\\trunk';
else
    m_str = sprintf('%strunk$', filesep());
end
if isempty(regexp(trunk, m_str, 'ONCE'))
    cd ..
end
cd ..
cd test_data
enc_opts = struct('process_color',true,...
  'msrmnt_mtrx',struct('type',{...
  'SensingMatrixWH', 'SensingMatrixLclWH','SensingMatrixNrWH',...
  'SensingMatrixDCT', 'SensingMatrixLclDCT','SensingMatrixNrDCT',...
  'SensingMatrixDFT', 'SensingMatrixLclDFT','SensingMatrixNrDFT',...
  'SensingMatrixMLSeqDC' ...
  },'args', struct()),...
  'blks_', {{...
  struct('blk_size',[0,0,4], 'sav_levels', 3), ...
  struct('blk_size',[72,88,4], 'blk_ovrlp', [0,0,0])}},...
  'blk_dur', 0, ...
  'zero_ext_f',[0,0,0], 'zero_ext_b', [0,0,0], ...
  'wrap_ext',{{[0,0,0],[10,10,0]}},...
  'n_frames', 8,...
  'msrmnt_input_ratio', 0.1, 'random',struct('seed',1000, 'type', 1),...
  'lossless_coder', '&CSVideoCodecInputOutputData.LLC_INT');
% enc_opts = struct('process_color',true,...
%   'msrmnt_mtrx',struct('type','SensingMatrixMLSeqDC','args', struct('rnd_type',1)),...
%   'blk_size',[0,0,4], 'sav_levels', 3, ...
%   'blk_dur', 0, ...
%   'zero_ext_f',[0,0,0], 'zero_ext_b', [0,0,0], ...
%   'wrap_ext',[0,0,0],...
%   'n_frames', 8,...
%   'msrmnt_input_ratio', 0.1, 'random',struct('seed',1000),...
%   'lossless_coder', '&CSVideoCodecInputOutputData.LLC_INT');
anls_opts = [];
% anls_opts = struct();

% dec_opts = struct('disp',0, 'expand_level', VidBlocker.BLK_STT_INTRPLT);
% dec_opts = struct('disp',1, 'expand_level', VidBlocker.BLK_STT_RAW, ...
%   'beta_A0', 0.01, 'beta_D0', 0.01, 'max_int_iters', 10, 'sparsifier', ...
%   struct('args', struct('b_stt', VidBlocker.BLK_STT_INTRPLT)));
% dec_opts = struct('disp',1, 'expand_level', VidBlocker.BLK_STT_RAW, ...
%   'beta_A0', 0.01, 'beta_D0', 0.01, 'max_int_iters', 4, 'max_iters',20, 'sparsifier', ...
%   struct('args', struct('b_stt', VidBlocker.BLK_STT_INTRPLT)));
% dec_opts = [];
dec_opts = struct('disp',0, 'expand_level', 4, 'sparsifier', ...
  struct('args', struct('b_stt',4)), 'whole_frames',false);
ids = struct('output','*','case','Mr<Mr>Q<Qm>,<Qa><Lc><Lg>');
files_def = '<foreman_news_io.json';
proc_opts = struct('report_blk', false,...
  'no_stats', false, 'par_blks', 4, 'par_cases', 10);

init_gpu(0)
tic
sml_io =  CSVidCodec.doSimulation(enc_opts,anls_opts,dec_opts,files_def, proc_opts);
toc
