[mpath,~,~] = fileparts(mfilename('fullpath'));
cd(mpath)
cd ..
if strcmp(filesep(),'\')
    m_str = '\\trunk$';
else
    m_str = sprintf('%strunk$', filesep());
end
trunk = pwd();
if isempty(regexp(trunk, m_str, 'ONCE'))
    cd ..
end
cd ..
cd test_data
enc_opts = struct(...
  'start_frame',113,......
  'n_frames',inf,...
  'blks_', struct(...
    'blk_size',{[36, 48, 8]},...
    'blk_ovrlp',{[0, 0, 0]},...
    'zero_ext_f',{[0, 0, 2]},...
    'wrap_ext',{[8, 8, 0]}),...
  'zero_ext_b',[0, 0, 0],...
  'blk_pre_diff',[0, 0, 0],...
  'process_color',true,...
  'random',struct('rpt_temporal',4),...
  'msrs_',{{...
    struct(...
      'msrmnt_mtrx', {{...              
        struct('type','SensingMatrixCnvlvRndDC'),...
        }},...
      'msrmnt_input_ratio',{{0.3, 0.2, 0.1}}...
      )...
    }},...
  'conv_mode',SensingMatrixConvolve.MODE_GLBL,...
      'conv_rng',[17, 17, 3],...
  'qntzr_wdth_mltplr', 1.0,...
  'qntzr_ampl_stddev', 3.0,...
  'lossless_coder',CSVideoCodecInputOutputData.LLC_AC...
);
% anls_opts = [];
anls_opts = struct('fxd_trgt',true,...  %  all shifts with same set of measurmements
    'nrm_exp',1,... % L1 norm in comparisons
    'm_range','&[6,6;2,2]', ...
    'm_step_numer','&[1,1;1,1]', ...
    'm_step_denom','&[1;2]', ...
    'ignore_edge',1,...
    'chk_bgrnd', struct('mx_avg',0, 'mn_dcd',2, 'thrsh', 2)...
    );
dec_opts = [];
io_types = {'input', 'enc_vid', 'inp_anls', 'inp_sav', 'inp_mark',...
    'inp_vanls', 'inp_vsav', 'inp_vmark', ...
    'enc_anls', 'enc_sav', 'enc_mark', 'mat', 'txt'};
proc_opts = struct(...
  'inp_anls', 2,...
  'case_id', '<Nn>-<Mt>_<Mr>_<Zf>', ...
  'prefix', '<Nn>-<Mt>_<Mr>_<Zf>]',...
  'output_id', '*', 'par_cases', 0, 'report_blk', true,...
  'io_types', {io_types});
files_def='<PETS2000_test_enc.json';
CSVidCodec.doSimulation(enc_opts, anls_opts, dec_opts, files_def,...
    proc_opts)
