[mpath,~,~] = fileparts(mfilename('fullpath'));
cd(mpath)
cd ..
cd ..
cd test_data
enc_opts = struct('msrmnt_mtrx',struct('type','SensingMatrixWH', 'args',struct()),...
    'blk_size','&[72 88 8]',...
    'msrmnt_input_ratio', {{0.05,0.10,0.15,0.20,0.25}},... 
    'random',struct('seed',1000),...
    'qntzr_wdth_mltplr', {{1, 5, 10, 20, 50}},...
    'lossless_coder', '&CSVideoCodecInputOutputData.LLC_AC'...
  );
anls_opts = [];
dec_opts = [];
ids = struct('output','std_cif_*','case','Mr<Mr2>Q<Qm1>');
files_def = '<std_cif_io.json';
proc_opts = struct('par_cases',25, 'prefix', '<Nn>-Mr<Mr2>Q<Qm1>]',...
  'case_id', '<Nn>-Mr<Mr2>Q<Qm1>');
sml_io =  CSVidCodec.doSimulation(enc_opts,[],dec_opts(),files_def, proc_opts);
