[mpath,~,~] = fileparts(mfilename('fullpath'));
cd(mpath)
cd ..
trunk = pwd;
fsep = filesep();
if strcmp(fsep,'\')
    m_str = '\\trunk$';
else
    m_str = sprintf('%strunk$', filesep());
end
if isempty(regexp(trunk, m_str, 'ONCE'))
    cd ..
end
cd ..
cd test_data
enc_opts = struct('msrmnt_mtrx',struct('type','SensingMatrixWH', 'args',struct()),...
    'blk_size','&[72 88 8]',...
    'n_frames',inf,...
    'msrmnt_input_ratio', 0.1, ...
    'random',struct('seed',1000),...
    'qntzr_wdth_mltplr', {{10, 5, 2, 1}},...
    'lossless_coder', '&CSVideoCodecInputOutputData.LLC_INT');
% enc_opts = struct(...
%     'msrmnt_mtrx',struct('type','SensingMatrixWH',...
%         'args',struct('rnd_type',1)),...
%     'blk_size','&[72 88 2]',...
%     'n_frames',2,...
%     'msrmnt_input_ratio', {0.25,0.15}, 'random',struct('seed',1000));
anls_opts = [];
dec_opts = [];
ids = struct('output','*','case','<Nn>-Mr<Mr>');
files_def = '<all_io.json';
proc_opts = struct();
sml_io =  CSVidCodec.doSimulation(enc_opts,[],dec_opts(),files_def, proc_opts);
