pets_test_start = tic;
[mpath,~,~] = fileparts(mfilename('fullpath'));
cd(mpath)
cd ..
trunk = pwd;
if strcmp(filesep(),'\')
    m_str = '\\trunk';
else
    m_str = sprintf('%strunk$', filesep());
end
if isempty(regexp(trunk, m_str, 'ONCE'))
    cd ..
end
cd ..
cd test_data
enc_opts = struct(...
  'start_frame',113,......
  'n_frames',inf,......
  'blk_size',[36, 48, 8],...
  'blk_ovrlp',[0, 0, 0],...
  'wnd_type', 0,...
  'zero_ext_f',[0, 0, 5],...
  'zero_ext_b',[0, 0, 0],...
  'wrap_ext',[16, 16, 0],...
  'blk_pre_diff',[0, 0, 0],...
  'process_color',true,...
  'random',struct('rpt_temporal',4),...
  'msrmnt_mtrx',struct('type','SensingMatrixNrDFT'),...
  'conv_mode',SensingMatrixConvolve.MODE_GLBL,...
  'conv_rng',[17, 17, 5],...
  'msrmnt_input_ratio',0.25,...
  'lossless_coder',CSVideoCodecInputOutputData.LLC_AC...
);

anls_opts = struct('fxd_trgt',true,'nrm_exp',1,...
    'm_range','&[6,6;2,2]', 'm_step_numer','&[1,1;1,1]', ...
    'm_step_denom','&[1;2]',...
    'chk_bgrnd', struct('mx_avg',0, 'mn_dcd',2, 'thrsh', 2)...
    );
% anls_opts = [];

dec_opts = [];
% dec_opts = struct('Q_msrmnts',0,'max_int_iters',4);
% dec_opts = struct();
proc_opts = struct('case_id', 'Mr<Mr><Ma>Q<Qm><Lc><Lg>', 'prefix', '] ');

files_def  = ['{'...
  '"names":["PETS2000_test"],'...
  '"types":[{"input":".json"},'... 
           '{"mat":".mat"},'... 
           '{"output":".o.yuv"},'...
           '{"inp_mark":".im.yuv"},'...
           '{"ref_mark":null},'...
           '{"dec_mark":null, "ignore":1},'...
           '{"dec_slct_mark":null},'...
           '{"dec_anls":null, "ignore":1},'...
           '{"dec_sav":null, "ignore":1},'...
           '{"inp_anls":".im.csv"},'...
           '{"inp_vanls":".imv.csv", "ignore":1},'...
           '{"enc_anls":".em.csv"},'...
           '{"inp_sav":".im.sav.txt"},'...
           '{"inp_vsav":".imv.sav.txt", "ignore":1},'...
           '{"enc_sav":".em.sav.txt"},'...
           '{"txt":".txt"},'...
           '{"enc_vid":".csvid"},'...
           '{"enc_pre_diff":".edff.yuv"},'...
           '{"dec_pre_diff":".ddff.yuv"},'...
           '{"tst_pre_diff":".dffo.yuv"},'...
           '{"err_pre_diff":".dffe.yuv"}],'...
  '"input_dir":"&pwd",'...
  '"output_dir":"&[pwd filesep ''..'' filesep ''output'' filesep ''mov_*'']",'...
  '"dec_dir":"dec_*",'...
  '"case_dir":"*.case"'...
'}'];
% files_def='<PETS2000_test_enc.json';
CSVidCodec.doSimulationCase(enc_opts, anls_opts, dec_opts, files_def,...
    proc_opts)
toc(pets_test_start);
