pets_test_start = tic;
[mpath,~,~] = fileparts(mfilename('fullpath'));
cd(mpath)
cd ..
trunk = pwd;
if strcmp(filesep(),'\')
    m_str = '\\trunk';
else
    m_str = sprintf('%strunk$', filesep());
end
if isempty(regexp(trunk, m_str, 'ONCE'))
    cd ..
end
cd ..
cd test_data
enc_opts = struct(...
  'start_frame',113,......
  'n_frames',inf,......
  'blk_size',[72, 96, 8],...
  'blk_ovrlp',[36, 48, 0],...
  'zero_ext_f',[8, 8, 5],...
  'zero_ext_b',[0, 0, 0],...
  'wrap_ext',[0, 0 0],...
  'blk_pre_diff',[0, 0, 0],...
  'process_color',true,...
  'random',struct('rpt_temporal',4),...
  'msrmnt_mtrx',struct('type','SensingMatrixNrDFT'),...
  'conv_mode',SensingMatrixConvolve.MODE_GLBL,...
  'conv_rng',[17, 17, 5],...
  'msrmnt_input_ratio',0.25,...
  'lossless_coder',CSVideoCodecInputOutputData.LLC_AC...
);

anls_opts = struct('fxd_trgt',true,'nrm_exp',1,...
    'm_range','&[6,6;2,2]', 'm_step_numer','&[1,1;1,1]', ...
    'm_step_denom','&[1;2]',...
    'chk_bgrnd', struct('mx_avg',0, 'mn_dcd',2, 'thrsh', 2)...
    );
% anls_opts = [];

dec_opts = [];
% dec_opts = struct('Q_msrmnts',0,'max_int_iters',4);
% dec_opts = struct();
proc_opts = struct('case_id', 'Mr<Mr><Ma>Q<Qm><Lc><Lg>', 'prefix', '] ');
files_def='<PETS2000_test_enc.json';
CSVidCodec.doSimulationCase(enc_opts, anls_opts, dec_opts, files_def,...
    proc_opts)
toc(pets_test_start);
