function [stats, enc_opts] = run_quant_test_NLR_CS(img_inp_dir, img_out_dir, prll)
  if nargin < 3
    prll = false;
  end
  img_out_dir = regexprep(img_out_dir, '*',...
      datestr(now,'yyyymmdd_HHMM'),'once');
  img_files = {...
    'barbara.tif', 'boats.tif',...
    'cameraman.tif', 'foreman.tif', 'house.tif', 'lena256.tif', ...
    'Monarch.tif', 'Parrots.tif', 'trui1.png' };
  img_files = arrayfun(@(x) {fullfile(img_inp_dir, x{1})}, img_files);
  
  q_step = [0.5 1 1.5 2 3 4];
  csr = [0.02:0.01:0.05, 0.06:0.02:0.10, 0.15:0.05:0.25];
  
%   enc_opts = struct(...
%     'msrmnt_input_ratio', {num2cell(csr)}, ...
%     'qntzr_wdth_mode', CS_EncParams.Q_WDTH_CSR, ...
%     'qntzr_wdth_mltplr', {num2cell(q_step)}, ...
%     'qntzr_ampl_stddev', 4,...
%     'qntzr_outrange_action', CS_EncImgParams.Q_SAVE,...
%     'msrmnt_mtrx', struct('type', {'SensingMatrixMD_WH' 'SensingMatrixMD_DCT' })...
%     );

  enc_opts = struct(...
    'msrmnt_input_ratio', {num2cell(csr)}, ...
    'qntzr_wdth_mode', CS_EncParams.Q_WDTH_CSR, ...
    'qntzr_wdth_mltplr', {num2cell(q_step)}, ...
    'msrmnt_mtrx', struct('type', {'MD_WH' 'MD_DCT', 'WH', 'DCT' })...
    );

%   dec_opts = struct('alg', {'GAP_TV', 'NLR_CS', 'DAMP', 'SLOPE'});
  dec_opts = struct('alg', {'GAP_TV', 'NLR_CS'});
  
  stats = test_quant_set(img_files, enc_opts, dec_opts, true, 1, img_out_dir, prll);
end
              
          
  
