function ok=chk_constraints(eps, beta, xerr, disp, prfx)
  ok = struct(...
    'A', (~eps.A_maxerr || norm(xerr.A,inf) < eps.A_maxerr) && ...
    (~eps.A_sqrerr ||  norm(xerr.A,2) <= eps.A_sqrerr),...
    'D', (~eps.D_maxerr ||  norm(xerr.D,inf) <= eps.D_maxerr) && ...
    (~eps.D_sqrerr ||  norm(xerr.D,2) <= eps.D_sqrerr));
  ok.all = ok.A && ok.D;
  if disp
    if ok.all
      ok_str = 'CONSTRAINTS MET';
    else
      ok_str = 'CONSTRAINTS NOT met';
    end
    beta_str = sprintf('%10.3g %10.3g', beta.A, beta.D);
    max_str = sprintf('%10.3g(%g) %10.3g(%g)', ...
      norm(xerr.A,inf), eps.A_maxerr, norm(xerr.D,inf), eps.D_maxerr);
    nrm_str = sprintf('%10.3g(%g) %10.3g(%g)', ...
      norm(xerr.A,2), eps.A_sqrerr, norm(xerr.D,2), eps.D_sqrerr);
    fprintf(['%sbeta=(%s), %s\n'...
      'max_err: %s   nrm_err: %s\n'],...
      prfx(),...
      beta_str, ok_str,...
      max_str, nrm_str);
  end
end
