
% This file builds the *.mex files used by class RndStrmC. the source C
% files and header files are the ones in this directory. To interface from
% a C program, use the files RndC_ifc.[hc].
% The C files here depend on C files and header files in ./cgen/lib.  Those
% files were generated by Matlab Coder from matlab files in ./cgen_src. The
% Matlab Coder project file is ./cgen_src/randgen.prj. Note that the
% following options were used in the building:
%   Matlab integer types (uint32) rather than C native types (unsigned int)
%   No provisions for Inf and NaN
%   No clamping of overflow at the maximum or minimum
%   The input type of the function arguments were uint32 scalars.

prev_dir = pwd();
[mpath,~,~] = fileparts(mfilename('fullpath'));
cd (mpath);
cgen_file_names = {...
    'rng.c', 'rand.c', 'randn.c', 'randperm.c', 'get_rand_data.c',...
    'get_rand_initialize.c', 'get_rand_emxutil.c', 'get_rand_emxAPI.c',...
    'eml_rand.c', 'eml_randn.c', 'eml_rand_shr3cong_stateful.c',...
    'eml_rand_mcg16807_stateful.c', 'eml_rand_mt19937ar_stateful.c'...
    };
cgen_dir = ['cgen',filesep(), 'lib'];
cgen_files = strcat(cgen_dir, filesep(), cgen_file_names);
common_args = {'common_RndC_mex.c', 'RndCState_mex.c', 'RndC_ifc.c', 'RndCState.c'};
% opts = {'-v', ['-I' cgen_dir]};
opts = {['-I' cgen_dir]};

args = [opts {'init_RndC_mex.c'} common_args cgen_files];
mex(args{:});

args = [opts {'rand_RndC_mex.c'} common_args cgen_files];
mex(args{:});

args = [opts {'randi_RndC_mex.c'} common_args cgen_files];
mex(args{:});

args = [opts {'randn_RndC_mex.c'} common_args cgen_files];
mex(args{:});

args = [opts {'randperm_RndC_mex.c'} common_args cgen_files];
mex(args{:});

cd(prev_dir);
